<h1> <font color='red'> DO read all the comments in the python code and contents in the markdown cells</font> </h1>

<pre><font size=4><b>
You can do this assignment in google colab itself. we have provided a notebook to use tensorboard in google colab itself.</b></font>
</pre>

In [1]:
import tensorflow as tf
#enabled to get instant output. if you don't need, you can use session concept which was dicussed in lecture videos. 

In [2]:
a = tf.random.uniform(shape=(1000,8,1,64))
b = tf.random.uniform(shape=(1000,8,1,64))
add =tf.concat([a,b],2)
print(add.shape)

(1000, 8, 2, 64)


## 1.1 Addition
<pre> It is similar to numpy addition.</pre>

In [3]:
a = tf.random.uniform(shape=(2,2))
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.6499524 , 0.16747773],
       [0.59671044, 0.8154198 ]], dtype=float32)>

In [4]:
b = tf.random.uniform(shape=(2,2))
b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.7495203 , 0.49469745],
       [0.57392097, 0.9673873 ]], dtype=float32)>

In [5]:
add = a + b

In [6]:
add

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.3994727, 0.6621752],
       [1.1706314, 1.7828071]], dtype=float32)>

<pre>Broadcasting works similar to numpy.</pre>

In [7]:
c = 2.0

In [8]:
add_2 = a + c

In [9]:
add_2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.6499524, 2.1674776],
       [2.5967104, 2.8154197]], dtype=float32)>

## 1.2 Subtraction
<pre> It is similar to numpy Subtraction.</pre>

In [10]:
a = tf.random.uniform(shape=(2,2))
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.17939949, 0.4045714 ],
       [0.7606307 , 0.03632987]], dtype=float32)>

In [11]:
b = tf.random.uniform(shape=(2,2))
b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.40210462, 0.68318295],
       [0.00102985, 0.40726674]], dtype=float32)>

In [12]:
sub = a - b

In [13]:
sub

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.22270513, -0.27861154],
       [ 0.7596009 , -0.37093687]], dtype=float32)>

## 1.3 Multiplication
<pre>
- For two dimensional matrices, you can multiply (m*n) and (n*p) and get (m*p)
- for 3 dim matrices, you can multiply (b * n * p)  and (b * p * m)  and get (b * n * m). ( for any dim, you have to maintain last 2 dim as two dim multiplication and first n-2 dim has to be same. you will get better idea if you gothrough    all the operation which we have written below.)
</pre>

In [14]:
a = tf.random.uniform(shape=(3,2))
a

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.9973576 , 0.4761908 ],
       [0.18193936, 0.13768744],
       [0.6251842 , 0.49971342]], dtype=float32)>

In [15]:
b = tf.random.uniform(shape=(2,4))
b

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0.8212011 , 0.9376087 , 0.87685764, 0.9662738 ],
       [0.99870837, 0.69951665, 0.4080813 , 0.8482678 ]], dtype=float32)>

In [16]:
tf.matmul(a, b)# (3*2)@(2*4) = (3*4)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1.2946069 , 1.2682346 , 1.0688652 , 1.3676578 ],
       [0.2869184 , 0.2669026 , 0.21572259, 0.29259908],
       [1.0124699 , 0.93573594, 0.7521212 , 1.0279899 ]], dtype=float32)>

In [17]:
a = tf.random.uniform(shape=(3,2,4))
a

<tf.Tensor: shape=(3, 2, 4), dtype=float32, numpy=
array([[[0.17811036, 0.28580666, 0.16233277, 0.42602408],
        [0.6194595 , 0.6819993 , 0.61603904, 0.8739135 ]],

       [[0.40818918, 0.9405874 , 0.8659258 , 0.6044761 ],
        [0.20482647, 0.07359517, 0.12711442, 0.43835557]],

       [[0.47314548, 0.69676065, 0.54311645, 0.4736526 ],
        [0.0257628 , 0.4826578 , 0.41990912, 0.97318375]]], dtype=float32)>

In [18]:
b = tf.random.uniform(shape=(3,4,3))
b

<tf.Tensor: shape=(3, 4, 3), dtype=float32, numpy=
array([[[0.55204403, 0.26463556, 0.7468889 ],
        [0.18534565, 0.7820047 , 0.8072634 ],
        [0.90029526, 0.701704  , 0.9371792 ],
        [0.78834355, 0.35477924, 0.9775859 ]],

       [[0.8973055 , 0.5912453 , 0.74950445],
        [0.04995251, 0.95794153, 0.71644044],
        [0.91508436, 0.06710386, 0.21256924],
        [0.3068931 , 0.6006814 , 0.20080769]],

       [[0.21216285, 0.56156325, 0.10620093],
        [0.8334284 , 0.99343157, 0.22544956],
        [0.40063727, 0.18249238, 0.9892124 ],
        [0.15096748, 0.23689616, 0.9017099 ]]], dtype=float32)>

In [19]:
tf.matmul(a, b) #(3*2*4)@(3*4*3) = (3*2*3)

<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
array([[[0.6332985 , 0.53569055, 0.93235993],
        [1.7119358 , 1.4395812 , 2.444885  ]],

       [[1.3911599 , 1.5635723 , 1.2852671 ],
        [0.4383169 , 0.46344447, 0.32129067]],

       [[0.9701828 , 1.1692063 , 1.1716876 ],
        [0.7228769 , 0.8011286 , 1.4044597 ]]], dtype=float32)>

In [20]:
a = tf.random.uniform(shape=(3,2,2,4))
a

<tf.Tensor: shape=(3, 2, 2, 4), dtype=float32, numpy=
array([[[[0.7184186 , 0.14843166, 0.71186244, 0.8527241 ],
         [0.30536866, 0.44231093, 0.4589758 , 0.55727077]],

        [[0.16869795, 0.24479806, 0.62146485, 0.30831254],
         [0.8377447 , 0.852216  , 0.4254843 , 0.77525747]]],


       [[[0.2052486 , 0.7190188 , 0.8543308 , 0.92802525],
         [0.1185323 , 0.20708907, 0.9091829 , 0.3118956 ]],

        [[0.59783125, 0.01476181, 0.04300439, 0.01374245],
         [0.6885321 , 0.17942297, 0.8384657 , 0.83359826]]],


       [[[0.4054352 , 0.36312008, 0.6979109 , 0.3803197 ],
         [0.09626126, 0.7653775 , 0.2049874 , 0.8765118 ]],

        [[0.4254043 , 0.38138497, 0.882324  , 0.8766757 ],
         [0.36564362, 0.15044034, 0.54328525, 0.82739305]]]],
      dtype=float32)>

In [21]:
b = tf.random.uniform(shape=(3,2,4,3))
b

<tf.Tensor: shape=(3, 2, 4, 3), dtype=float32, numpy=
array([[[[0.4411626 , 0.7209413 , 0.6599796 ],
         [0.7556913 , 0.9659275 , 0.9132501 ],
         [0.14837885, 0.47183418, 0.7352481 ],
         [0.2661444 , 0.93835616, 0.39484167]],

        [[0.49822116, 0.6981957 , 0.0848527 ],
         [0.6514456 , 0.78200924, 0.57456756],
         [0.94715416, 0.6714953 , 0.2333901 ],
         [0.5267391 , 0.532832  , 0.32587743]]],


       [[[0.08916867, 0.99705637, 0.8560989 ],
         [0.32848668, 0.50349927, 0.89392745],
         [0.7025205 , 0.7224016 , 0.4031911 ],
         [0.6416093 , 0.8364837 , 0.31542957]],

        [[0.14763308, 0.7753153 , 0.17125785],
         [0.86503696, 0.02571177, 0.39216113],
         [0.4859295 , 0.38635266, 0.34214747],
         [0.6847409 , 0.8668537 , 0.4736582 ]]],


       [[[0.15213776, 0.37999249, 0.9236163 ],
         [0.98919713, 0.15013218, 0.27335262],
         [0.48181164, 0.63145936, 0.72944903],
         [0.22130704, 0.09622037, 0.15854

In [22]:
tf.matmul(a,b) # (3*2*2*4)@(3*2*4*3)=(3*2*2*3)

<tf.Tensor: shape=(3, 2, 2, 3), dtype=float32, numpy=
array([[[[0.761681  , 1.7973518 , 1.4697833 ],
         [0.6853845 , 1.386872  , 1.1629725 ]],

        [[0.99454486, 0.89080805, 0.40048334],
         [1.7839123 , 1.9501432 , 0.91268337]]],


       [[[1.4501044 , 1.9601178 , 1.455649  ],
         [0.9174301 , 1.1401434 , 0.7515535 ]],

        [[0.13133629, 0.49241483, 0.12939537],
         [1.2350917 , 1.5849938 , 0.8699988 ]]],


       [[[0.8413084 , 0.68587524, 1.0431154 ],
         [1.0644977 , 0.36526585, 0.58662266]],

        [[1.6989546 , 1.0743165 , 1.1912557 ],
         [1.1823033 , 0.7414621 , 0.8904124 ]]]], dtype=float32)>

## 1. 4 Transpose
<pre>    - matrix transpose. </pre>

In [23]:
a = tf.random.uniform(shape=(3,2))
a

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.46587265, 0.1408552 ],
       [0.62029564, 0.4903072 ],
       [0.74175525, 0.09108174]], dtype=float32)>

In [24]:
a.shape

TensorShape([3, 2])

In [25]:
tf.transpose(a)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.46587265, 0.62029564, 0.74175525],
       [0.1408552 , 0.4903072 , 0.09108174]], dtype=float32)>

<pre>We have a "perm" argument for transpose function, in that you can define your own way to change rows and column positions. as shown below</pre>

In [26]:
a = tf.random.uniform(shape=(3,2,5,4))
a.shape

TensorShape([3, 2, 5, 4])

In [27]:
a_transpose = tf.transpose(a, perm=[0, 2, 1, 3])

In [28]:
a_transpose.shape

TensorShape([3, 5, 2, 4])

<pre>My transposed matrix dim changed based on pem values( we transposed 1 and 2 axis only). you can check below example in that we chnaged all the axis</pre>

In [29]:
a = tf.random.uniform(shape=(3,2,5,4))
a.shape

TensorShape([3, 2, 5, 4])

In [30]:
a_transpose = tf.transpose(a, perm=[3, 2, 1, 0])

In [31]:
a_transpose.shape

TensorShape([4, 5, 2, 3])

## 1. 4 Element wise operation

### 1.4.1 Multiply Respective elements in two matrices
Ex: 
<pre>
A = [[1 2],
     [3,4]]

B = [[5,6],
     [7,8]]

we want A*B as 
[A[0][0]*B[0][0], A[0][1]*B[0][1]
A[1][0]*B[1][0], A[1][1]*B[1][1]]
</pre>

In [32]:
a = tf.random.uniform(shape=(3,2))
a

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.5384263 , 0.06602383],
       [0.44988608, 0.8570112 ],
       [0.804605  , 0.16969979]], dtype=float32)>

In [33]:
b = tf.random.uniform(shape=(3,2))
b

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.14350879, 0.8242574 ],
       [0.4843732 , 0.95032823],
       [0.02389646, 0.11150312]], dtype=float32)>

In [34]:
a * b

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.07726891, 0.05442063],
       [0.21791276, 0.8144419 ],
       [0.01922721, 0.01892206]], dtype=float32)>

In [35]:
tf.multiply(a, b)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.07726891, 0.05442063],
       [0.21791276, 0.8144419 ],
       [0.01922721, 0.01892206]], dtype=float32)>

<pre>You can do a*b or you can use tf.multiply</pre>

## 1.5 Expanding Dimensions

In [36]:
a = tf.random.uniform(shape=(3,2))
a.shape

TensorShape([3, 2])

In [37]:
a_add = tf.expand_dims(a, axis=1)#we are adding an additional axis at 1st dim

In [38]:
a_add.shape

TensorShape([3, 1, 2])

In [39]:
a = tf.random.uniform(shape=(3,2))
a.shape

TensorShape([3, 2])

In [40]:
a_add = tf.expand_dims(a, axis=2)#we are adding an additional axis at 2nd dim

In [41]:
a_add.shape

TensorShape([3, 2, 1])

## 1.6 Squeezing dimensions

<pre>
Note that we can squeeze along with the axis with shape 1

Ex: 
A.shape= [3,4,1] ==> we can squeez it on axis=2 will give [3,4]
A.shape= [3,1,4] ==> we can squeez it on axis=1 will give [3,4]
A.shape= [1,3,4] ==> we can squeez it on axis=0 will give [3,4]
A.shape= [2,3,4] ==> we can't squeez it on any of the axis

</pre>

In [42]:
a = tf.random.uniform(shape=(3,1,4))
a.shape

TensorShape([3, 1, 4])

In [43]:
a_squ = tf.squeeze(a, axis=1)

In [44]:
a_squ

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.38707352, 0.37173057, 0.19045103, 0.6189842 ],
       [0.5428276 , 0.9659871 , 0.95560646, 0.38637507],
       [0.7443099 , 0.92989135, 0.49952495, 0.93732953]], dtype=float32)>

## 1.7 Reshaping of tensors

<a href='https://www.tensorflow.org/api_docs/python/tf/reshape'> check the documentation </a>

In [45]:
a = tf.random.uniform(shape=(5,3,4))

# tf.reshape(tensor, [reshape dimensions]])
b = tf.reshape(a, [a.shape[0]*a.shape[1],a.shape[2]])

print(a.shape, b.shape)

(5, 3, 4) (15, 4)


# 2. Call Backs

In [46]:
import numpy as np
import pandas as pd

In [47]:
(X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data()
# if you observe the input shape its 3 dimensional vector
# for each image we have a (28*28) vector
# we will convert the (28*28) vector into single dimensional vector of 1 * 784 
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1]*X_train.shape[2]) 
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1]*X_test.shape[2]) 
Y_train = tf.keras.utils.to_categorical(y_train, 10) 
Y_test = tf.keras.utils.to_categorical(y_test, 10)

11501568/11490434 [==============================] - 2s 0us/step


In [48]:
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(60000, 784)
(10000, 784)
(60000, 10)
(10000, 10)


In [49]:
from tensorflow.keras.layers import Dense,Input,Activation
from tensorflow.keras.models import Model
import random as rn

## 2.1 Writing custom call backs

<pre>In Keras, Callback is a python class meant to be subclassed to provide specific functionality, <br> with a set of methods called at various stages of training (including batch/epoch start and ends), <br> testing, and predicting. Callbacks are useful to get a view on internal states and statistics of the model during training</pre>

<pre>
<b>Writing Call Backs</b> - You can inherit from <b>`tf.keras.callbacks.Callback`</b>,<br> Copied the code for callback class from tensorflow documentation and pased in below cell, you can check that code. <br>It has many methods like batch/epoch_begin/end. so you can do manipulate the model parameters or <br>print the required outputs using these methods.<br> The `logs` dict contains the loss value, and all the metrics at the end of a batch or epoch

</pre>
> <a href='https://www.w3schools.com/python/python_inheritance.asp'> Do Read this Blog to understand how to inhert other classes </a>

In [ ]:
class Callback(object):
    
    """Abstract base class used to build new callbacks.
      Attributes:
          params: dict. Training parameters
              (eg. verbosity, batch size, number of epochs...).
          model: instance of `keras.models.Model`.
              Reference of the model being trained.
          validation_data: Deprecated. Do not use.
      The `logs` dictionary that callback methods
      take as argument will contain keys for quantities relevant to
      the current batch or epoch.
      Currently, the `.fit()` method of the `Model` class
      will include the following quantities in the `logs` that
      it passes to its callbacks:
          on_epoch_end: logs include `acc` and `loss`, and
          optionally include `val_loss`
          (if validation is enabled in `fit`), and `val_acc`
          (if validation and accuracy monitoring are enabled).
          on_batch_begin: logs include `size`,
          the number of samples in the current batch.
          on_batch_end: logs include `loss`, and optionally `acc`
            (if accuracy monitoring is enabled).
      """

    def __init__(self):
        self.validation_data = None
        self.model = None
        # Whether this Callback should only run on the chief worker in a
        # Multi-Worker setting.
        # TODO(omalleyt): Make this attr public once solution is stable.
        self._chief_worker_only = None

    def set_params(self, params):
        self.params = params

    def set_model(self, model):
        self.model = model

    def on_batch_begin(self, batch, logs=None):
        """A backwards compatibility alias for `on_train_batch_begin`."""

    def on_batch_end(self, batch, logs=None):
        """A backwards compatibility alias for `on_train_batch_end`."""

    def on_epoch_begin(self, epoch, logs=None):
        """Called at the start of an epoch.
        Subclasses should override for any actions to run. This function should only
        be called during TRAIN mode.
        Arguments:
            epoch: integer, index of epoch.
            logs: dict. Currently no data is passed to this argument for this method
              but that may change in the future.
        """

    def on_epoch_end(self, epoch, logs=None):
        """Called at the end of an epoch.
        Subclasses should override for any actions to run. This function should only
        be called during TRAIN mode.
        Arguments:
            epoch: integer, index of epoch.
            logs: dict, metric results for this training epoch, and for the
              validation epoch if validation is performed. Validation result keys
              are prefixed with `val_`.
        """

    def on_train_batch_begin(self, batch, logs=None):
        """Called at the beginning of a training batch in `fit` methods.
        Subclasses should override for any actions to run.
        Arguments:
            batch: integer, index of batch within the current epoch.
            logs: dict. Has keys `batch` and `size` representing the current batch
              number and the size of the batch.
        """
        # For backwards compatibility.
        self.on_batch_begin(batch, logs=logs)

    def on_train_batch_end(self, batch, logs=None):
        """Called at the end of a training batch in `fit` methods.
        Subclasses should override for any actions to run.
        Arguments:
            batch: integer, index of batch within the current epoch.
            logs: dict. Metric results for this batch.
        """
        # For backwards compatibility.
        self.on_batch_end(batch, logs=logs)

    def on_test_batch_begin(self, batch, logs=None):
        """Called at the beginning of a batch in `evaluate` methods.
        Also called at the beginning of a validation batch in the `fit`
        methods, if validation data is provided.
        Subclasses should override for any actions to run.
        Arguments:
            batch: integer, index of batch within the current epoch.
            logs: dict. Has keys `batch` and `size` representing the current batch
                  number and the size of the batch.
        """

    def on_test_batch_end(self, batch, logs=None):
        """Called at the end of a batch in `evaluate` methods.
        Also called at the end of a validation batch in the `fit`
        methods, if validation data is provided.
        Subclasses should override for any actions to run.
        Arguments:
            batch: integer, index of batch within the current epoch.
            logs: dict. Metric results for this batch.
        """

    def on_predict_batch_begin(self, batch, logs=None):
        """Called at the beginning of a batch in `predict` methods.
        Subclasses should override for any actions to run.
        Arguments:
            batch: integer, index of batch within the current epoch.
            logs: dict. Has keys `batch` and `size` representing the current batch
                  number and the size of the batch.
        """

    def on_predict_batch_end(self, batch, logs=None):
        """Called at the end of a batch in `predict` methods.
        Subclasses should override for any actions to run.
        Arguments:
            batch: integer, index of batch within the current epoch.
            logs: dict. Metric results for this batch.
        """

    def on_train_begin(self, logs=None):
        """Called at the beginning of training.
        Subclasses should override for any actions to run.
        Arguments:
            logs: dict. Currently no data is passed to this argument for this method
                  but that may change in the future.
        """

    def on_train_end(self, logs=None):
        """Called at the end of training.
        Subclasses should override for any actions to run.
        Arguments:
            logs: dict. Currently no data is passed to this argument for this method
                  but that may change in the future.
        """

    def on_test_begin(self, logs=None):
        """Called at the beginning of evaluation or validation.
        Subclasses should override for any actions to run.
        Arguments:
            logs: dict. Currently no data is passed to this argument for this method
              but that may change in the future.
        """

    def on_test_end(self, logs=None):
        """Called at the end of evaluation or validation.
        Subclasses should override for any actions to run.
        Arguments:
            logs: dict. Currently no data is passed to this argument for this method
              but that may change in the future.
        """

    def on_predict_begin(self, logs=None):
        """Called at the beginning of prediction.
        Subclasses should override for any actions to run.
        Arguments:
            logs: dict. Currently no data is passed to this argument for this method
              but that may change in the future.
        """

    def on_predict_end(self, logs=None):
        """Called at the end of prediction.
        Subclasses should override for any actions to run.
        Arguments:
            logs: dict. Currently no data is passed to this argument for this method
              but that may change in the future.
    """

# <font color='red'> 2.1.1 Custom callbacks for performace metrices </font>

In [ ]:
from sklearn.metrics import recall_score
class LossHistory(tf.keras.callbacks.Callback):
    def __init__(self,validation_data):
      self.x_test = validation_data[0]
      self.y_test= validation_data[1]
    def on_train_begin(self, logs={}):
        ## on begin of training, we are creating a instance varible called history
        ## it is a dict with keys [loss, acc, val_loss, val_acc]
        self.history={'loss': [],'accuracy': [],'val_loss': [],'val_accuracy': [],'val_recall': []}
        
    def on_epoch_end(self, epoch, logs={}):
        true_positives=0
        ## on end of each epoch, we will get logs and update the self.history dict
        self.history['loss'].append(logs.get('loss'))
        self.history['accuracy'].append(logs.get('accuracy'))
      
        if logs.get('val_loss', -1) != -1:
            self.history['val_loss'].append(logs.get('val_loss'))
        if logs.get('val_accuracy', -1) != -1:
            self.history['val_accuracy'].append(logs.get('val_accuracy'))
        # we can get a list of all predicted values at the end of the epoch
        # we can use these predicted value and the true values to calculate any custom evaluation score if it is needed for our model
        # Here we are taking log of all true positives and then taking average of it
        y_pred= self.model.predict(self.x_test)
        y_label_pred=np.argmax(y_pred,axis=1)
        custom_score = np.log(np.sum(y_test== y_label_pred))/len(y_test)
        
        #we can also calcualte predefined metrics such as precison, recall, etc. using callbacks 
        recall = recall_score(y_test,y_label_pred,average='micro')
        self.history['val_recall'].append(recall)
        print('custom_Score: ',np.round(custom_score,5),'Recall: ',recall)
            
history_own=LossHistory(validation_data=[X_test,y_test])            

> in the above function we have written logs={}, which means the logs is a dictionary and the keys present will the same values that gets printed while you train your model i.e model.fit()
<img src='https://i.imgur.com/fAiHfe7.png'>

In [ ]:
#Input layer
input_layer = Input(shape=(784,))
#Dense hidden layer
layer1 = Dense(50,activation='sigmoid',kernel_initializer=tf.keras.initializers.glorot_normal(seed=30))(input_layer)
#output layer
output = Dense(10,activation='softmax',kernel_initializer=tf.keras.initializers.glorot_normal(seed=0))(layer1)
#Creating a model
model = Model(inputs=input_layer,outputs=output)


#Callbacks
history_own=LossHistory(validation_data=[X_test,y_test])            

optimizer = tf.keras.optimizers.Adam(0.01)

model.compile(optimizer=optimizer, loss='categorical_crossentropy',metrics=['accuracy'])

model.fit(X_train,Y_train,epochs=3, validation_data=(X_test,Y_test), batch_size=16, callbacks=[history_own])


In [ ]:
history_own.history

# <font color='red'> 2.1.2 Writing the call back to terminate training if loss is 'NaN'</font>

In [ ]:
class TerminateNaN(tf.keras.callbacks.Callback):
        
    def on_epoch_end(self, epoch, logs={}):
        loss = logs.get('loss')
        if loss is not None:
            if np.isnan(loss) or np.isinf(loss):
                print("Invalid loss and terminated at epoch {}".format(epoch))
                self.model.stop_training = True

# <font color='red'> 2.2 Using tensorflow call backs </font>

There are some callbacks which are implemented in the Tensorflow

## <b> 2.2.1 ModelCheckpoint</b> - Save the model after every epoch. You can check documentation <a href="https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/ModelCheckpoint">here</a>

In [ ]:
from tensorflow.keras.callbacks import ModelCheckpoint

In [ ]:
#Input layer
input_layer = Input(shape=(784,))
#Dense hidden layer
layer1 = Dense(50,activation='sigmoid',kernel_initializer=tf.keras.initializers.glorot_normal(seed=30))(input_layer)
#output layer
output = Dense(10,activation='softmax',kernel_initializer=tf.keras.initializers.glorot_normal(seed=0))(layer1)
#Creating a model
model = Model(inputs=input_layer,outputs=output)


#Callbacks
#file path, it saves the model in the 'model_save' folder and we are naming model with epoch number 
#and val acc to differtiate with other models
#you have to create model_save folder before running the code.
filepath="model_save/weights-{epoch:02d}-{val_accuracy:.4f}.hdf5"
checkpoint = ModelCheckpoint(filepath=filepath, monitor='val_loss',  verbose=1, save_best_only=True, mode='auto')

optimizer = tf.keras.optimizers.Adam(0.01)

model.compile(optimizer=optimizer,
              loss='categorical_crossentropy',metrics=['accuracy'])

model.fit(X_train,Y_train,epochs=5,validation_data=(X_test,Y_test),batch_size=16,callbacks=[checkpoint])

<pre>If you need 4th epoch model, you can load that model as below. It saves optimizer state as well. so noo need to recompile. </pre>

In [ ]:
model.load_weights('model_save/weights-04-0.7914.hdf5')#change this with your name which you got in above output

In [ ]:
model.fit(X_train,Y_train)

## 2.2.2 EarlyStopping:

<pre>Stop training when a monitored quantity has stopped improving. You can check the documentatin <a href="https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/EarlyStopping">here</a></pre>

In [ ]:
from tensorflow.keras.callbacks import EarlyStopping

In [ ]:
#Input layer
input_layer = Input(shape=(784,))
#Dense hidden layer
layer1 = Dense(50,activation='sigmoid',kernel_initializer=tf.keras.initializers.glorot_normal(seed=30))(input_layer)
#output layer
output = Dense(10,activation='softmax',kernel_initializer=tf.keras.initializers.glorot_normal(seed=0))(layer1)
#Creating a model
model = Model(inputs=input_layer,outputs=output)

#you can monitor any quantity (here i am monitoring val_loss), you can give any number for patience based on your need. 
#i am terminating training if my validation loss incresing at once than previous loss. so maintained 1. you can give min delta
#an absolute change of less than min_delta, will count as no improvement. i maintained 0.35 because i don't want to run 
#so many epoch to see termination
earlystop = EarlyStopping(monitor='val_loss', min_delta=0.35, patience=1, verbose=1)

optimizer = tf.keras.optimizers.Adam(0.01)

model.compile(optimizer=optimizer,
              loss='categorical_crossentropy',metrics=['accuracy'])

model.fit(X_train,Y_train,epochs=10,validation_data=(X_test,Y_test),batch_size=16,callbacks=[earlystop])

<pre>It stopped at 2nd epoch only. You can use this early stopping to get best model than overfitted model</pre>

## 2.2.3 LearningRateScheduler:
<pre>You can schedule learning rate for every epoch. You can decrease or increase the learning rate based on epoch number. </pre> 

In [ ]:
from tensorflow.keras.callbacks import LearningRateScheduler

In [ ]:
def changeLearningRate(epoch):
    #here we are performing exponential decay of the learning rate
    initial_learningrate=0.1
    changed = initial_learningrate*(1-0.1)**epoch
    return changed

In [ ]:
changed_lr = []
for i in range(1,50):
    changed_lr.append(changeLearningRate(i))

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

In [ ]:
plt.plot(changed_lr)
plt.ylabel('learning_rate')
plt.xlabel('epoch number')

If you check above figure, learning rate is decreasing if my epoch number is increasing. We are using same function to schedule our learning rate based on epoch number. You can write your own function or you can write custom call back to decrease the learning rate based on val_loss/acc. 
In the above function, we have implemented exponential decay with decay rate 0.1, you can check that <a href="https://mathbitsnotebook.com/Algebra2/Exponential/EXGrowthDecay.html">here</a>

In [ ]:
#Input layer
input_layer = Input(shape=(784,))
#Dense hidden layer
layer1 = Dense(50,activation='sigmoid',kernel_initializer=tf.keras.initializers.glorot_normal(seed=30))(input_layer)
#output layer
output = Dense(10,activation='softmax',kernel_initializer=tf.keras.initializers.glorot_normal(seed=0))(layer1)
#Creating a model
model = Model(inputs=input_layer,outputs=output)

lrschedule = LearningRateScheduler(changeLearningRate, verbose=1)

model.compile(optimizer=tf.keras.optimizers.Adam(0.1),
              loss='categorical_crossentropy',metrics=['accuracy'])

model.fit(X_train,Y_train,epochs=3,validation_data=(X_test,Y_test),batch_size=16,callbacks=[lrschedule])

## 2.2.4 ReduceLROnPlateau
It is similar to EarlyStopping, you can reduce your Learning rate by some factor if my val_loss/acc is not improving. You can check the documentation <a href="https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/ReduceLROnPlateau">here</a>

<pre>There are many pre built call backs are available in Tensorflow, you can check those in <a href="https://www.tensorflow.org/api_docs/python/tf/keras/callbacks">this</a> link.

You can give as many callbacks you want while training the model as given below.</pre>

In [ ]:
#Input layer
input_layer = Input(shape=(784,))
#Dense hidden layer
layer1 = Dense(50,activation='sigmoid',kernel_initializer=tf.keras.initializers.glorot_normal(seed=30))(input_layer)
#output layer
output = Dense(10,activation='softmax',kernel_initializer=tf.keras.initializers.glorot_normal(seed=0))(layer1)
#Creating a model
model = Model(inputs=input_layer,outputs=output)

#create a call back list
lrschedule = LearningRateScheduler(changeLearningRate, verbose=0.1)
earlystop = EarlyStopping(monitor='val_loss', min_delta=0.25, patience=1, verbose=1)
filepath="model_save/weights-{epoch:02d}-{val_accuracy:.4f}.hdf5"
checkpoint = ModelCheckpoint(filepath=filepath, monitor='val_loss', verbose=1, 
                             save_best_only=True, mode='auto')


# here we are creating a list with all the callbacks we want
callback_list = [lrschedule, earlystop, checkpoint]


model.compile(optimizer=tf.keras.optimizers.Adam(0.1),
              loss='categorical_crossentropy',metrics=['accuracy'])

model.fit(X_train,Y_train,epochs=5,validation_data=(X_test,Y_test),batch_size=16,callbacks=callback_list)